CREATE TABLE TB_USER (
                         id             NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                         name           VARCHAR2(255) NOT NULL,
                         email          VARCHAR2(255) NOT NULL,
                         password_hash  VARCHAR2(255) NOT NULL,
                         zip_code       VARCHAR2(20)  NOT NULL,
                         city           VARCHAR2(255),
                         state          VARCHAR2(2),
                         role           VARCHAR2(20)  NOT NULL,
                         created_at     TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                         CONSTRAINT pk_user PRIMARY KEY (id),
                         CONSTRAINT uq_user_email UNIQUE (email),
                         CONSTRAINT ck_user_role CHECK (role IN ('ADMIN', 'USER'))
);

CREATE TABLE TB_SERVICE (
                            id            NUMBER(19)     GENERATED BY DEFAULT AS IDENTITY,
                            provider_id   NUMBER(19)     NOT NULL,
                            title         VARCHAR2(255)  NOT NULL,
                            description   VARCHAR2(2000) NOT NULL,
                            category      VARCHAR2(255)  NOT NULL,
                            price         NUMBER(10, 2)  NOT NULL,
                            status        VARCHAR2(20)   NOT NULL,
                            created_at    TIMESTAMP      DEFAULT CURRENT_TIMESTAMP,
                            CONSTRAINT pk_service PRIMARY KEY (id),
                            CONSTRAINT fk_service_provider FOREIGN KEY (provider_id) REFERENCES TB_USER (id),
                            CONSTRAINT ck_service_status CHECK (status IN ('ACTIVE', 'PAUSED', 'CLOSED')),
                            CONSTRAINT ck_service_price CHECK (price >= 0)
);

CREATE TABLE TB_CONTRACT (
                             id           NUMBER(19)    GENERATED BY DEFAULT AS IDENTITY,
                             service_id   NUMBER(19)    NOT NULL,
                             client_id    NUMBER(19)    NOT NULL,
                             status       VARCHAR2(20)  NOT NULL,
                             created_at   TIMESTAMP     DEFAULT CURRENT_TIMESTAMP,
                             CONSTRAINT pk_contract PRIMARY KEY (id),
                             CONSTRAINT fk_contract_service FOREIGN KEY (service_id) REFERENCES TB_SERVICE (id),
                             CONSTRAINT fk_contract_client FOREIGN KEY (client_id) REFERENCES TB_USER (id),
                             CONSTRAINT ck_contract_status CHECK (status IN ('REQUESTED', 'ACCEPTED', 'COMPLETED', 'CANCELLED'))
);

CREATE INDEX idx_service_provider ON TB_SERVICE (provider_id);
CREATE INDEX idx_contract_service ON TB_CONTRACT (service_id);
CREATE INDEX idx_contract_client ON TB_CONTRACT (client_id);